name: release

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build package for Release.
      run: dotnet pack -c Release
      if: github.event.action == 'published'
    - name: Push package to nuget.
      run: dotnet nuget push **/AspNetCore.Proxy.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://www.nuget.org/api/v2/package
      if: github.event.action == 'published'
      
